# Generated by Django 5.0.3 on 2024-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verify",
            field=models.BooleanField(default=False),
        ),
    ]
