# Generated by Django 5.0.4 on 2024-04-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('day_to_do', models.DateField()),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False)),
                ('tag', models.TextField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
