# Generated by Django 5.0.4 on 2024-04-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tasks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
    ]
