# Generated by Django 5.0.4 on 2024-04-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.TextField(blank=True),
        ),
    ]
