# Generated by Django 5.0.4 on 2024-04-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_tasks_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='username',
            field=models.TextField(blank=True),
        ),
    ]
